### ISSUE TITLE
Amazing plug in but..

### ISSUE THREAD

**Issue by Pishky** [austensatterlee/MIDI-Transformer#2] opened 2021-10-22 18:56 UTC
It works as advertised and is **amazing.** 
One problem is that if I have it on one track for instance with another instrument and duplicate this tract then the plug in crashes in the duplicate. 

Am I using it wrong or is it a genuine bug.
Cheers from 

PK
p.p.kohout@gmail.com

**Comment by austensatterlee** [comment] 2021-10-22 20:20
Interesting, this sounds to me like an actual bug. I'll try replicating it and taking a look this weekend. Thanks for bringing this up!

**Comment by Pishky** [comment] 2021-10-22 20:51
Hi Austen,

Many thanks for your reply.
First of all I don't want to sound like the many other whining people out
there on the Internet.
It is a phenomenal piece of software as it stands, no ands ifs or buts.

In the simplest instance, I drag it onto an instrument, it works
beautifully.
I save the project.
When I open the project again and click on the vst then it crashes. I have
tried it in BitWig and Reaper with the same result.

It also does not like to be duplicated as in having more than one instance
in a session. Sometimes it works but sometimes it does crash again and will
not save properly.

Hope this helps and finds you well

Warm regards

Peter

**Comment by austensatterlee** [comment] 2021-10-25 00:49
This is exactly the right place to whine! I really do appreciate you bringing this up, and have been able to reproduce the crashes you describe. It looks like it's probably related to the serialization code (saving/loading plugin states), but I'm still looking into how to fix it. I'll update this thread once I discover more.

Thanks again!

**Comment by austensatterlee** [comment] 2021-10-26 22:53
Hey Peter, I took a closer look at this and believe it should be fixed with the latest commit (tested in Reaper). I updated the download link in the README to the latest version (https://static.kvraudio.com/files/4296/midi-transformer-0_9_1.zip), so feel free to grab it and let me know if you're still having issues.

**Comment by Pishky** [comment] 2021-10-27 03:10
I will take a look at it as soon as I get home from work. Thanks for update. 

Out of interest being an amateur programmer myself how do you make something like that? 
Are you going from a template? C++?
Would you consider selling it for money??
The GUIs and capabilities of VST plugins blow my mind

Take care 
Peter

**Comment by austensatterlee** [comment] 2021-10-27 03:40
If you're familiar with C++, getting started isn't too hard. This plugin uses JUCE, which is a fairly popular C++ framework for audio plugin development (another contender is a free framework called IPlug). The frameworks do basically provide a template to make it easier to get started. If you're interested I'd recommend taking a look at the [JUCE tutorials](https://juce.com/learn/tutorials) (the [plugin examples](https://docs.juce.com/master/tutorial_plugin_examples.html) tutorial has some sample projects to get started with).

It can be a really fun project since you get to see and hear the fruits of your labor :-)

Regarding whether or not I'd consider selling the software, I don't plan on doing so with this particular plugin.

**Comment by Pishky** [comment] 2021-10-27 10:48
Good evening Austen.

Thank you for the info in your last email. I had a quick look and thought
'wow!' looks pretty complicated but exciting as well.

I eagerly downloaded the new version of the MIDI transformer and put it
through the loop.
Verdict. Works like a charm!!
I can save projects with it, duplicate channels, change settings and it
saves and reopens without a glitch. The best thing is that
the settings are now saved as well.

Congratulations!

One more observation. When I drop it onto a track first it does not
register MIDI input on its own and does not work till a second instrument
is in the same channel. Is this by design?
In Bitwig it is registered as an Audio plug in and not an instrument.

I have spent literally three months looking for a VST like this. My primary
keyboard is not capable of generating a MIDI velocity of more than 60 and
it caused me problems no end. There is something similar in Ableton and
supposedly in Cubase. The one in Cubase is ridiculously complicated and
does not work like yours.

I think it is a top notch product.

I hope that you keep coding and hopefully make a lot of money out of it.

All the best

Peter

**Comment by austensatterlee** [comment] 2021-10-28 05:37
Thanks for the kind words, and I'm especially glad to hear it helped solved a real problem for you.

I'll close this particular issue thread for now, but feel free to post a new issue anytime you've found a new bug. In the mean time, I'll try and replicate the issue you mentioned regarding MIDI messages not registering.

**Comment by austensatterlee** [comment] 2021-11-10 06:52
*Reopening for now to follow up on the issue of MIDI events not registering in certain edge cases*

@Pishky To directly answer your question, that behavior is not by design. However, when I open up a track in Reaper with just this plugin it does seem to register MIDI events correctly (seen from the visual indicator in the plugin's graph). Does this issue only occur for you in Bitwig?

Also, just out of curiosity, do you have a use case in mind for using the plugin by itself on a track? The only case I can think of is if you wanted to route the plugin's output to a different track. I'm sure there are more I'm not thinking of however.

**Closed as completed** 2022-07-05 06:57 UTC
